name: Deploy CodeIgniter to cPanel

on:
  push:
    branches:
      - main   # change if you use another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: 📂 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          server-dir: /  # adjust to your CodeIgniter root
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/tests/*
